Task1
SaintSkat/symfonyStud pull request #1
Opened 2024-11-04 11:23 UTC by SaintSkat

2024-12-03 06:31 UTC, praisethedeviI requested changes
В PR вешаем Assignee себя, меня Reviewer

Если нет возможности повесть меня в ревьюеры, то надо зайти в настройки репозитория и выдать коллаборатора

---
А так почти все супер

2024-12-03 06:31 UTC, praisethedeviI commented on .env
> +DATABASE_URL="postgresql://user:password@127.0.0.1:5432/symfony_db?serverVersion=15&charset=utf8"
user, password и app_db надо было указать тоже переменными в .env

То есть
```
DATABASE_USER=user
DATABASE_PASSWORD=password
DATABASE_DB=app_db
```
Эти же переменные прокинуть в docker_compose.yml, прописав там ${DATABASE_DB} и тд

Также, мы никаких данных не пишем в .env (только сами названия переменных), мы создаем отдельный файл .env.local, который не попадает в контроль версий. С этим файлом и работаем

2024-12-03 06:31 UTC, praisethedeviI commented on .idea/.gitignore
Файлы .idea не должны попадать в репозиторий. Это IDE специфичные файлы. Надо добавить директорию в гитигнор

2024-12-03 06:31 UTC, praisethedeviI commented on docker/docker-compose.yml
> +      POSTGRES_PASSWORD: password
Тут надо указать переменные окружения

2024-12-03 06:31 UTC, praisethedeviI commented on migrations/Version20241104151943.php
Все миграции можно было объединить в один файл в рамках этой задачи, но не критично

2024-12-03 06:31 UTC, praisethedeviI commented on src/Repository/ProjectGroupRepository.php
> +    //     * @return ProjectGroup[] Returns an array of ProjectGroup objects
Комментарии можно удалить

2024-12-03 06:31 UTC, praisethedeviI commented on src/Repository/ProjectRepository.php
> +    //     * @return Project[] Returns an array of Project objects
И тут

2024-12-03 06:31 UTC, praisethedeviI commented on src/Repository/TaskRepository.php
> +    //    public function findByExampleField($value): array
И тут

2025-02-04 13:50 UTC, SaintSkat commented on src/Repository/ProjectGroupRepository.php
> +    //     * @return ProjectGroup[] Returns an array of ProjectGroup objects
\+

2025-02-04 13:51 UTC, SaintSkat commented on src/Repository/ProjectRepository.php
> +    //     * @return Project[] Returns an array of Project objects
\+

2025-02-04 13:51 UTC, SaintSkat commented on src/Repository/TaskRepository.php
> +    //    public function findByExampleField($value): array
\+

2025-02-04 13:51 UTC, SaintSkat commented on .idea/.gitignore
\+

2025-02-04 19:48 UTC, SaintSkat commented on .env
> +DATABASE_URL="postgresql://user:password@127.0.0.1:5432/symfony_db?serverVersion=15&charset=utf8"
\+

2025-02-04 19:53 UTC, SaintSkat commented on migrations/Version20241104151943.php
\+

2025-02-04 19:53 UTC, praisethedeviI approved these changes

2025-02-08 06:40 UTC, merged